# Welcome to Jekyll!
#
# Site settings

title: Obviously Awesome
description: ""
email: bjpcjp@gmail.com
author: Brian Piercy
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bjpcjp.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll_social_icons

social_links:
  twitter: https://twitter.com/brianpiercy
  github: https://github.com/bjpcjp
  linkedin: https://linkedin.com/in/brianpiercy

# excerpt visibility
show_excerpts: true 

# navigation links
header_pages:
  - about.html 
  - math.html # titled as algorithms
  - behaviors.html
  - cmos.html # titled as chips
  - gametheory.html
  - golang.html
  - ideas.html
  - devops.html # was linux.html
  - prodmgmt.html
  - python.html 
  - rails.html
  - storytelling.html
  - uiux.html # titled as ui/ux.html
  - webdev.html # titled as web tech
  - posts-by-tag.html


# algolia search plugin API:
algolia:
  #application_id: 0ST64V6V0J
  #index_name: jekyll
  #search_only_api_key: e850d8fbd248c7d7df4a35544f104d32
  #
  #extensions_to_index:
  #  - html
  #  - md 
  #  - txt 
    #- pdf
    #- ipynb
    #
#  nodes_to_index: 'p,div.card,div.textcard,blockquote'
  
# pagination:
#paginate: 20
#paginate_path: "/page:num/"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

disqus:
  shortname: brianpiercy